version: '3.8'

services:
  
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb_local
    ports:
      - "8000:8000"
    command: -jar DynamoDBLocal.jar -sharedDb
    volumes:
      - ./data/dynamodb:/home/dynamodblocal/data
    networks:
      - helina-network

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566" # Porta principal dos serviços da AWS simulados
    environment:
      - SERVICES=s3,sns,ssm,secretsmanager
      - DEFAULT_REGION=sa-east-1
      - EDGE_PORT=4566
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./data/localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - helina-network

networks:
  helina-network:
    driver: bridge
