aws:
  region: sa-east-1
  access-key: test
  secret-key: test

  dynamodb:
    endpoint: http://localhost:4566
    region: sa-east-1

  s3:
    bucket-name: usuario-profile-picture

  sns:
    topic-arn: arn:aws:sns:sa-east-1:000000000000:notifica-reserva

jwt:
  secret: Úh0WemNNA4Str1àÇda
  expiration: 60000

spring:

  application:
    name: helina